version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/contracts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/dashboard"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/veritas-dashboard"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/user-dashboard"
    schedule:
      interval: "weekly"
